/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.jooqGen;


import edu.java.domain.jooq.jooqGen.tables.Chat;
import edu.java.domain.jooq.jooqGen.tables.Chatandlink;
import edu.java.domain.jooq.jooqGen.tables.Databasechangelog;
import edu.java.domain.jooq.jooqGen.tables.Databasechangeloglock;
import edu.java.domain.jooq.jooqGen.tables.Link;
import edu.java.domain.jooq.jooqGen.tables.Linkstackoverflow;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chat</code>.
     */
    public static final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>public.chatandlink</code>.
     */
    public static final Chatandlink CHATANDLINK = Chatandlink.CHATANDLINK;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.link</code>.
     */
    public static final Link LINK = Link.LINK;

    /**
     * The table <code>public.linkstackoverflow</code>.
     */
    public static final Linkstackoverflow LINKSTACKOVERFLOW = Linkstackoverflow.LINKSTACKOVERFLOW;
}
