app:
  scheduler:
    enable: true
    interval: 15000
    force-check-delay: 15000
  stackoverlowlink: ${STACKOVERFLOW_DEFAULT_LINK:https://api.stackexchange.com/2.3/}
  githublink: ${GITHUB_DEFAULT_LINK:https://api.github.com}


spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
