/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.jooqGen.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chatandlink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkid;
    private Long chatid;

    public Chatandlink() {}

    public Chatandlink(Chatandlink value) {
        this.linkid = value.linkid;
        this.chatid = value.chatid;
    }

    @ConstructorProperties({ "linkid", "chatid" })
    public Chatandlink(
        @NotNull Long linkid,
        @NotNull Long chatid
    ) {
        this.linkid = linkid;
        this.chatid = chatid;
    }

    /**
     * Getter for <code>public.chatandlink.linkid</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkid() {
        return this.linkid;
    }

    /**
     * Setter for <code>public.chatandlink.linkid</code>.
     */
    public void setLinkid(@NotNull Long linkid) {
        this.linkid = linkid;
    }

    /**
     * Getter for <code>public.chatandlink.chatid</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatid() {
        return this.chatid;
    }

    /**
     * Setter for <code>public.chatandlink.chatid</code>.
     */
    public void setChatid(@NotNull Long chatid) {
        this.chatid = chatid;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Chatandlink other = (Chatandlink) obj;
        if (this.linkid == null) {
            if (other.linkid != null)
                return false;
        }
        else if (!this.linkid.equals(other.linkid))
            return false;
        if (this.chatid == null) {
            if (other.chatid != null)
                return false;
        }
        else if (!this.chatid.equals(other.chatid))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkid == null) ? 0 : this.linkid.hashCode());
        result = prime * result + ((this.chatid == null) ? 0 : this.chatid.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chatandlink (");

        sb.append(linkid);
        sb.append(", ").append(chatid);

        sb.append(")");
        return sb.toString();
    }
}
