/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.jooqGen.tables;


import edu.java.domain.jooq.jooqGen.Keys;
import edu.java.domain.jooq.jooqGen.Public;
import edu.java.domain.jooq.jooqGen.tables.Chat.ChatPath;
import edu.java.domain.jooq.jooqGen.tables.Link.LinkPath;
import edu.java.domain.jooq.jooqGen.tables.records.ChatandlinkRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chatandlink extends TableImpl<ChatandlinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chatandlink</code>
     */
    public static final Chatandlink CHATANDLINK = new Chatandlink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatandlinkRecord> getRecordType() {
        return ChatandlinkRecord.class;
    }

    /**
     * The column <code>public.chatandlink.linkid</code>.
     */
    public final TableField<ChatandlinkRecord, Long> LINKID = createField(DSL.name("linkid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chatandlink.chatid</code>.
     */
    public final TableField<ChatandlinkRecord, Long> CHATID = createField(DSL.name("chatid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Chatandlink(Name alias, Table<ChatandlinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Chatandlink(Name alias, Table<ChatandlinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chatandlink</code> table reference
     */
    public Chatandlink(String alias) {
        this(DSL.name(alias), CHATANDLINK);
    }

    /**
     * Create an aliased <code>public.chatandlink</code> table reference
     */
    public Chatandlink(Name alias) {
        this(alias, CHATANDLINK);
    }

    /**
     * Create a <code>public.chatandlink</code> table reference
     */
    public Chatandlink() {
        this(DSL.name("chatandlink"), null);
    }

    public <O extends Record> Chatandlink(Table<O> path, ForeignKey<O, ChatandlinkRecord> childPath, InverseForeignKey<O, ChatandlinkRecord> parentPath) {
        super(path, childPath, parentPath, CHATANDLINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChatandlinkPath extends Chatandlink implements Path<ChatandlinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChatandlinkPath(Table<O> path, ForeignKey<O, ChatandlinkRecord> childPath, InverseForeignKey<O, ChatandlinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChatandlinkPath(Name alias, Table<ChatandlinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChatandlinkPath as(String alias) {
            return new ChatandlinkPath(DSL.name(alias), this);
        }

        @Override
        public ChatandlinkPath as(Name alias) {
            return new ChatandlinkPath(alias, this);
        }

        @Override
        public ChatandlinkPath as(Table<?> alias) {
            return new ChatandlinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @NotNull
    public UniqueKey<ChatandlinkRecord> getPrimaryKey() {
        return Keys.CHATANDLINK_PKEY;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatandlinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHATANDLINK__CHATANDLINK_LINKID_FKEY, Keys.CHATANDLINK__CHATANDLINK_CHATID_FKEY);
    }

    private transient LinkPath _link;

    /**
     * Get the implicit join path to the <code>public.link</code> table.
     */
    public LinkPath link() {
        if (_link == null)
            _link = new LinkPath(this, Keys.CHATANDLINK__CHATANDLINK_LINKID_FKEY, null);

        return _link;
    }

    private transient ChatPath _chat;

    /**
     * Get the implicit join path to the <code>public.chat</code> table.
     */
    public ChatPath chat() {
        if (_chat == null)
            _chat = new ChatPath(this, Keys.CHATANDLINK__CHATANDLINK_CHATID_FKEY, null);

        return _chat;
    }

    @Override
    @NotNull
    public Chatandlink as(String alias) {
        return new Chatandlink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Chatandlink as(Name alias) {
        return new Chatandlink(alias, this);
    }

    @Override
    @NotNull
    public Chatandlink as(Table<?> alias) {
        return new Chatandlink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chatandlink rename(String name) {
        return new Chatandlink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chatandlink rename(Name name) {
        return new Chatandlink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chatandlink rename(Table<?> name) {
        return new Chatandlink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Chatandlink where(Condition condition) {
        return new Chatandlink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Chatandlink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Chatandlink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Chatandlink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Chatandlink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Chatandlink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Chatandlink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public Chatandlink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Chatandlink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public Chatandlink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
