/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.jooqGen.tables.records;


import edu.java.domain.jooq.jooqGen.tables.Chat;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChatRecord extends UpdatableRecordImpl<ChatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chat.chatid</code>.
     */
    public void setChatid(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chat.chatid</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatid() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatRecord
     */
    public ChatRecord() {
        super(Chat.CHAT);
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    @ConstructorProperties({ "chatid" })
    public ChatRecord(@NotNull Long chatid) {
        super(Chat.CHAT);

        setChatid(chatid);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatRecord
     */
    public ChatRecord(edu.java.domain.jooq.jooqGen.tables.pojos.Chat value) {
        super(Chat.CHAT);

        if (value != null) {
            setChatid(value.getChatid());
            resetChangedOnNotNull();
        }
    }
}
